# generated by datamodel-codegen:
#   filename:  relationship.schema.json
#   timestamp: 2025-12-12T03:24:46+00:00

from __future__ import annotations

from pydantic import BaseModel, Field
from typing import Any

class Relationship(BaseModel):
    source_id: str = Field(..., description='ID of the source component.')
    target_id: str = Field(..., description='ID of the target component.')
    description: str = Field(
        ..., description="Description of the interaction (e.g., 'Sends email to')."
    )
    protocol: str | None = Field(
        None, description="Communication protocol (e.g., 'gRPC', 'HTTPS')."
    )
    tags: list[str] | None = None
    metadata: dict[str, Any] = Field(
        default_factory=dict, description="Rich metadata (properties, style, etc)."
    )
