# generated by datamodel-codegen:
#   filename:  view_config.schema.json
#   timestamp: 2025-12-12T03:24:46+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, Literal

from pydantic import BaseModel, Field


class Type(Enum):
    c4_context = 'c4_context'
    c4_container = 'c4_container'
    sequence = 'sequence'
    flowchart = 'flowchart'
    flowchart_swimlane = 'flowchart_swimlane'


class Filters(BaseModel):
    tags: list[str] | None = None
    include_external: bool | None = True


class ViewConfig(BaseModel):
    key: str = Field(..., description='Unique key for this view configuration.')
    title: str = Field(..., description='Title to display on the diagram.')
    type: Type = Field(..., description='Type of diagram to generate.')
    scope_id: str | None = Field(
        None, description="ID of the component to focus on (for container/component views)."
    )
    filters: Filters = Field(
        default_factory=Filters, description="Filters like tags, include_external."
    )
    # Visual Configuration
    theme: dict[str, str] = Field(
        default_factory=dict, description="Mermaid theme variables (primaryColor, etc.)."
    )
    layout: dict[str, str] = Field(
        default_factory=dict, description="Layout config (direction: TB/LR, etc.)."
    )
    show_legend: bool = Field(True, description="Whether to display a legend.")
    group_by: str | None = Field(None, description="Field to group components by (e.g. 'owner', 'system').")
    flow_id: str | None = Field(None, description="ID of the flow to render (for sequence diagrams).")
    mermaid_config: dict[str, Any] = Field(
        default_factory=dict, description="Mermaid frontmatter config (e.g. layout: elk)."
    )
    abstraction_level: Literal['system', 'container', 'component'] | None = Field(
        None, description="Level of abstraction to roll up to (system=Root Group, container=L1 Group)."
    )
